global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-github-enterprise
  regions:
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests:
  github:
    parameter_input: github-enterprise-input.json
    template_file: quickstart-github-enterprise-master.template
